### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by jonasohland** [mbredel/thesis-template#11]
Hello and thank you for the fantastic template!

The link to _Richtlinien zur Anfertigung der Bachelorarbeit_ on line [166](https://github.com/mbredel/thesis-template/blame/ac9d8f74a54187387dd72d640dd2a7a7e76e3b4f/README.md#L166) seems to be broken. Would be great to have this replaced.

**Comment by mbredel** [comment]
Updated the broken link to the current guide.
