### ISSUE TITLE
Umlauts in thesis title not working

### ISSUE THREAD

**Issue by saitho** [mbredel/thesis-template#4]
My thesis title happens to have umlauts. I'm writing on MacOS and discovered that umlauts in the thesis title are not properly handled. In the text it's working fine.

I suppose that's because the hdathesis-config which includes the title is included before the classicthesis-config which contains the enconding definitions. Switching the includes in thesis.tex resolved my problem.

**Comment by mbredel** [comment]
Thank you very much for the hint. This problem is already described in the Readme.md in section "Umlauts". But I will have a look at your proposed solutions.

**Comment by saitho** [comment]
While switching the includes seems to work for the umlauts in the title, it does lead to another error with the hypersetup configuration in classicthesis-config. So for now I'll do as described in the README. :)
