### ISSUE TITLE
Publish Dockerimages with and without ghostscript

### ISSUE THREAD

**Issue by aeimer** [mbredel/thesis-template#9]
I have bould a gitlab-ci pipeline which builds the project and keeps the pdf-artifact, so I have always the same build env. I will use only these pdfs to share them with others. Furthermore there is the git-tag included and the buildtime, so i always know which version the pdf has.

To do this I need the Dockerimage WITH ghostscript, I published that under https://hub.docker.com/r/aeimer/thesis-template-ghostsctipt. I would be great if you could also provide a second version on your repo like:
- mbredel/thesis-template:2.0
- mbredel/thesis-template:2.0-ghostscript
and so on

Best regards
Alex

**Comment by mbredel** [comment]
All Docker images now come with Ghostscript.
